services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer:4-standalone
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KEY_SIZE: ${KEY_SIZE}
      CONNECTION_STRING: ${CONNECTION_STRING}
    ports:
      - "${PORT}:8000"
    depends_on:
      - postgres
    